### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by younghyopark** [otaheri/GRIP#1]
Very cool work!  Do you have any expected timeline of code release?

**Comment by otaheri** [comment]
Thanks for your interest @younghyopark. I am currently working on this, but there are some complications; hopefully by mid-April it should be released.

**Comment by ghpkishore** [comment]
@otaheri the weights are also not available on the webpage even after signing in. Is there any update on when you would be able to release the code and the weights. This is a very good paper.

**Comment by YalimD** [comment]
Hello @otaheri, thanks for the great work. Is there any update on releasing the weights? Thank you

**Comment by otaheri** [comment]
@YalimD @ghpkishore @younghyopark Sorry for any inconvenience, there were some issues with the server, but the files should be available now. Please let me know if there are any issues. 

Thanks a lot
